production: 
  adapter: postgresql
  encoding: unicode
  database: Design_Studio_Production
  pool: 5
  password:
	
development:
  adapter: postgresql
  encoding: unicode
  database: Design_Studio_Development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Design_Studio_Testing
  pool: 5
  password:
